package datatype

type DSTProperty int

const (
	DST_ROOT DSTProperty = iota
	DST_INDEX
	DST_OPERAND
	DST_TARGET
	DST_VALUE
	DST_DOWNTO
	DST_UPTO
	DST_CONDITION
	DST_PARAMETER
	DST_DECLARE
	DST_EXECUTE
	DST_THEN
	DST_ELSE
	DST_FROM
)

type DSTNodeType int

const (
	DST_CHAR_LITERAL DSTNodeType = iota
	DST_STR_LITERAL
	DST_INT_LITERAL
	DST_REAL_LITERAL
	DST_BOOL_LITERAL
	DST_ADD_OPERATOR
	DST_SUB_OPERATOR
	DST_MUL_OPERATOR
	DST_MOD_OPERATOR
	DST_DIV_OPERATOR
	DST_AND_OPERATOR
	DST_OR_OPERATOR
	DST_EQ_OPERATOR
	DST_NE_OPERATOR
	DST_GT_OPERATOR
	DST_LT_OPERATOR
	DST_GE_OPERATOR
	DST_LE_OPERATOR
	DST_NOT_OPERATOR
	DST_NEG_OPERATOR
	DST_CAST_OPERATOR
	DST_ASSIGNMENT_OPERATOR
	DST_ARRAY_ELEMENT
	DST_RECORD_FIELD
	DST_PROCEDURE_CALL
	DST_FUNCTION_CALL
	DST_BLOCK
	DST_IF_BLOCK
	DST_FOR_BLOCK
	DST_WHILE_BLOCK
	DST_CONST
	DST_TYPE
	DST_VARIABLE
	DST_FUNCTION
	DST_PROCEDURE
	DST_CONSTANT_DECLARATIONS
	DST_TYPE_DECLARATIONS
	DST_VARIABLE_DECLARATIONS
	DST_SUBPROGRAM_DECLARATIONS
	DST_PROGRAM
)

type DecoratedSyntaxTree struct {
	Property DSTProperty
	SelfType DSTNodeType
	Data     int
	Children []DecoratedSyntaxTree
}
